# Generated by Django 4.2.4 on 2023-08-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referral_code', models.CharField(max_length=8, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.appusers')),
            ],
        ),
    ]
