# Generated by Django 4.2.4 on 2023-08-11 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_app', '0002_alter_referralcodes_user_id_delete_appusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcodes',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
