# Generated by Django 4.2.4 on 2023-08-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_alter_referralcodes_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralcodes',
            old_name='user_id',
            new_name='username',
        ),
    ]
