# Generated by Django 4.2.4 on 2023-08-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_rename_user_id_referralcodes_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralcodes',
            old_name='username',
            new_name='user_id',
        ),
    ]
