# Generated by Django 4.2.4 on 2023-08-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_rename_username_referralcodes_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcodes',
            name='total_referrals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
